apiVersion: v1
kind: Service
metadata: 
  name: g3-coffeebreak-service
spec:
  ports:
    - port: 8080
  selector: 
    app: g3-coffeebreak
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: g3-coffeebreak-deployment
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: g3-coffeebreak
  template:
    metadata:
      labels: 
        app: g3-coffeebreak
    spec: 
      containers: 
      - name: bachelor
        image: xmimmer/coffeebreaktest
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: g3-coffeebreak
  namespace: group3
spec:
  tls:
    - hosts:
      - group3.sempro0.uvm.sdu.dk
      secretName: my-tls-secret
  rules:
   - host: group3.sempro0.uvm.sdu.dk
     http:
       paths: 
       - path: /
         backend:
           serviceName: g3-coffeebreak-service
           servicePort: 8080
        